language: bash
sudo: required

env:
  global:
  - secure: "kcS5f9JFCvMcFbVWtYYq2cpCmiyALJomcaQAHT6s4JxPTEtFtNtY1/WMYFZyzHNS+yvSsHh/WZTuyn1dr+B+TYXH2jjgjBdGsQWckDgjZT8MoPnHtd8zDtn0jwA2jTZ0n4S8BFQzwughOspebBoohS3CpGS8MZRHfSoc6J+CBXSCSG/Kz61dpkW9vlx2eRnJpP3prOjCnpStRe0eUtbxBTBvH6X5SNJweOAChzw24QxPQSbrfRh13/n8OVjr0QzzymCyQFSDPk89ULzua4/B5X4YmOIVRpD4Swn9szyp4wPiBDY271ciRrrMUOhjjbZ0Hm9aavlV/i0diGdDMI3a8bYzzMm1KSw7z2SY1GNdPDYeUikBtClw3LAIkTR6wjeSbmsm5y3qJuEjbn7/i6sVJeRKDjecGIvLhpBhQhnmwoLX7XUclCMX3e0ho4V0k62wHT6biUB8xEKfLgWrtcYJenJo5xRNDGkYhkXaNLA2qM3i5/LgOJmmi3vwZq9vV1Ppr5aFJNx/ayvxKJZjWoeEjeNCz0iZugCjD5j/lONTWfSryf7Fe3vn4mnpX5QD4DT5cgQe3XeXFg1HJIyzJgugkKxv96b6qulqyFXhQPBBFSJHHLJFYvhVdV721xqErEoaQYYnTfkt4s9Zhc/ue8pJL1q2HDjPUt46zpMO+3Qd+E4=" # DOCKER_USER
  - secure: "L++ZPG8+Ud7ZYuJP3OjshnERvBCZgF+8uIwwPDOUPMsiLhcLaf1pTya9PIzNC/4Ws4w8JSSYYcChDceknx71n2wccn+b0wSNWl9KSIqCl9Ra6tdzZMRNZZZRLDLO44A4hlXHKbs/qtCJhQS75TVyPq8XdKxhJiQmnp73XU5WODaF+NTUgUt4sS820UorbmAGosLlNr7RQJN/+57wWgMDYyVLKmn0e0ex/Ijk7A/yue1uAgWm0b7+PxFxfsR0gr/jzKMlCSNI4Ch1qIvJq0RwcF8y4ko7Y10DGM4CJC58L0/1Nv6FZx4ZjmzBWKp7BuM9fqLk5Fip4BRSvY2vazfmRTUvu9iqP+Z+W5LhxINIkLaNv7PyK2gJjdshzYLBkVmKl+EC7oADVB9qoyXH2XVkuuFa/e3pJZSB6d2s+pUaP8aOF00H5o/b553vk7BjPl6Xl/T7hSq21tKASgoLMIvUfOamGnrDHt6PHFrDdDjkF/P4XugLpuTxEAm7+GSKQ8B98tlNurLZ2G3S/pRF5R0Ib/ZPLiC90kLSBeClNk0kFxuAj7Qv1QgzbKbsc3ZBsU29I/nvsUPsR5YlgZCwZXZlqyGGHJiwOyaknX2ky8VsgwyZTrA3Op051TOuWnsOFSpKm2pEYt+Kd1P0cMt5b+eJKbqrKguYQthWqZMmOKmCUTs=" # DOCKER_PASS

branches:
  only:
    - master

services:
  - docker

before_script: 

script:
  - bash ./unifi/mock_test.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/ubiquiti-docker
  - make -C unifi build
  - 'if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi'
  - bash ./unifi-video/mock_test.sh
  - make -C unifi-video build
  - 'if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi-video release; fi'

after_success: 
