language: bash
sudo: required

env:
  global:
  - secure: "" # DOCKER_USER
  - secure: "" # DOCKER_PASS
  - secure: "" # DOCKER_EMAIL

branches:
  only:
    - master

services:
  - docker

before_script: 

script:
  - bash ./unifi/mock_test.sh
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/ubiquiti-docker
  - make -C unifi build
  - 'if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi'
  - bash ./unifi-video/mock_test.sh
  - make -C unifi-video build
  - 'if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi-video release; fi'

after_success: 
